export const FILTER_ARTICLES = 'FILTER_ARTICLES';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const ARTICLE_DETAIL = 'ARTICLE_DETAIL';
export const ADD_ARTICLE = 'ADD_ARTICLE';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
